import React, { useEffect, useState } from "react";
import { approvePTRescheduleRequest, getMyPTRescheduleRequests, rejectPTRescheduleRequest } from "../../services/ptService";
import { showAppToast } from "../../utils/appToast";
import "./PTRequests.css";

const fmt = (v) => { if (!v) return "—"; const d = new Date(v); return Number.isNaN(d.getTime()) ? String(v) : d.toLocaleString("vi-VN"); };

export default function PTRescheduleRequestsPage(){
  const [rows,setRows]=useState([]); const [loading,setLoading]=useState(true); const [noteMap,setNoteMap]=useState({});
  const load = async()=>{ setLoading(true); try{ const res=await getMyPTRescheduleRequests(); setRows(Array.isArray(res?.data?.data)?res.data.data:[]);}catch(e){ showAppToast({type:"error",title:"Đổi lịch",message:e?.response?.data?.message||"Không tải được yêu cầu đổi lịch"}); }finally{ setLoading(false);} };
  useEffect(()=>{ load(); },[]);
  const submit = async(row, action)=>{ const note = String(noteMap[row.id]||"").trim(); if(!note){ showAppToast({type:"error",title:"Đổi lịch",message:"Vui lòng nhập lý do cụ thể"}); return; } try { if(action==="approve") await approvePTRescheduleRequest(row.id,{note}); else await rejectPTRescheduleRequest(row.id,{note}); showAppToast({type:"success",title:"Đổi lịch",message: action==="approve" ? "Đã chấp nhận yêu cầu" : "Đã từ chối yêu cầu"}); await load(); } catch(e){ showAppToast({type:"error",title:"Đổi lịch",message:e?.response?.data?.message||"Không xử lý được yêu cầu"}); } };
  return <div className="ptr-wrap"><div className="ptr-toprow"><h2 className="ptr-title">Yêu cầu đổi lịch</h2></div><div className="ptr-card">{loading ? <div className="ptr-empty">Đang tải...</div> : !rows.length ? <div className="ptr-empty">Chưa có yêu cầu đổi lịch nào.</div> : <div className="ptr-list">{rows.map((row)=>{ const booking=row.Booking||{}; const member=booking.Member?.User?.username||`Member #${booking.memberId||"?"}`; const canAct=String(row.status||"").toLowerCase()==="pending"; return <div key={row.id} className="ptr-item"><div className="ptr-item-head"><div><div className="ptr-item-title">{member}</div><div className="ptr-item-meta">{booking.Package?.name||"Gói tập"} • {booking.Gym?.name||"Gym"}</div></div><span className={`ptr-badge status-${String(row.status||"").toLowerCase()}`}>{row.status}</span></div><div className="ptr-item-reason">Lịch cũ: {booking.bookingDate} {String(booking.startTime||"").slice(0,5)} - {String(booking.endTime||"").slice(0,5)}</div><div className="ptr-item-reason">Lịch mới: {row.requestedDate} {String(row.requestedStartTime||"").slice(0,5)} - {String(row.requestedEndTime||"").slice(0,5)}</div><div className="ptr-item-reason">Lý do hội viên: {row.reason || "—"}</div><div className="ptr-item-reason">Gửi lúc: {fmt(row.createdAt)}</div>{canAct ? <><textarea className="ptr-textarea" placeholder="Nhập lý do cụ thể khi chấp nhận hoặc từ chối" value={noteMap[row.id]||""} onChange={(e)=>setNoteMap((p)=>({...p,[row.id]:e.target.value}))} /><div className="ptr-item-actions"><button className="ptr-btn primary" onClick={()=>submit(row,'approve')}>Chấp nhận</button><button className="ptr-btn danger" onClick={()=>submit(row,'reject')}>Từ chối</button></div></> : <div className="ptr-item-reason">Phản hồi PT: {row.trainerResponseNote || "—"}</div>}</div>;})}</div>}</div></div>;
}
